version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/core"
    commit-message:
      prefix: "deps[core]: "
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "06:00"
  - package-ecosystem: "cargo"
    directory: "/bindings/node"
    commit-message:
      prefix: "deps[node]: "
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "06:05"
  - package-ecosystem: "npm"
    directory: "/bindings/node"
    commit-message:
      prefix: "deps[node]: "
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "06:10"
  - package-ecosystem: "cargo"
    directory: "/bindings/wasm"
    commit-message:
      prefix: "deps[cargo:wasm]: "
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "06:15"
  - package-ecosystem: "npm"
    directory: "/bindings/wasm"
    commit-message:
      prefix: "deps[node:wasm]: "
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "06:20"
  - package-ecosystem: "cargo"
    directory: "/bindings/java"
    commit-message:
      prefix: "deps[java]: "
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "06:25"